# -*- coding: utf-8 -*-
"""First Stage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhSV5l64rIot36eeKAJMeXc-X-gitBD2
"""

# Install ML/Stats libraries
!pip install scikit-learn statsmodels joblib --quiet

# Install base libraries
!pip install psycopg2-binary sqlalchemy pandas numpy --quiet

import pandas as pd
import numpy as np
import sys
import joblib # New for model persistence (MLOps)
from sqlalchemy import create_engine
import re # NEW: Required for the robust string extraction fix

# Scikit-learn imports for advanced modeling and preprocessing
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler # NEW: Essential for KNN
from sklearn.neighbors import KNeighborsRegressor # NEW: User requested model
from sklearn.ensemble import RandomForestRegressor # NEW: Strong benchmark model
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

# -----------------------------
# Configuration (Your Neon Details)
# -----------------------------
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_C9aUQXVxSGE6"
DB_HOST = "ep-cold-paper-adut66se-pooler.c-2.us-east-1.aws.neon.tech"
DB_NAME = "neondb"

# Construct the connection URL
DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}?sslmode=require&channel_binding=require"


# --- GLOBAL FUNCTION DEFINITION (Required for apply() call in 2.1) ---
def extract_trip_id(trip_id_raw):
    """
    Extracts numeric part from a string like 'T12'. Handles nulls robustly.
    This function must be defined globally to resolve the NameError.
    """
    s = str(trip_id_raw)

    # Search for the numeric pattern. If s is 'nan' or 'None', match will be None.
    match = re.search(r'(\d+)', s)

    # Return the result or np.nan
    return int(match.group(1)) if match else np.nan
# --- END GLOBAL FUNCTION ---

print("--- 💾 Loading Cleaned Data from Neon PostgreSQL ---")

try:
    engine = create_engine(DATABASE_URL)

    # Load primary analytical tables
    df_trips = pd.read_sql("SELECT * FROM trips", engine)
    df_drivers = pd.read_sql("SELECT * FROM drivers", engine)
    df_cars = pd.read_sql("SELECT * FROM cars", engine)

    # NEW: Load events_mixed temporarily to access the raw timestamp for completed trips
    df_events_raw = pd.read_sql("SELECT trip_id, timestamp, event_type FROM events_mixed WHERE event_type = 'TRIP_END'", engine)

    print("✅ Data loading complete.")
    print(f"Trips loaded: {len(df_trips)} rows.")

except Exception as e:
    print(f"❌ Error loading data from Neon: {e}")
    sys.exit(1)

# Convert trip_id from df_events_raw to numeric format to match df_trips' cleaned format

# Now calling the globally defined function: extract_trip_id()
df_events_raw['trip_id_num'] = df_events_raw['trip_id'].apply(extract_trip_id)

# CRITICAL FIX: Drop the original trip_id string column to ensure unique column labels
# before renaming and sorting, resolving the ValueError.
df_events_raw.drop(columns=['trip_id'], inplace=True)

df_events_raw['trip_id_num'] = pd.to_numeric(df_events_raw['trip_id_num'], errors='coerce')
df_events_raw.dropna(subset=['trip_id_num'], inplace=True)
df_events_raw.rename(columns={'trip_id_num': 'trip_id'}, inplace=True)

# --- FIX: Deduplicate df_events_raw to prevent merge error ---
# Convert timestamp to datetime (required for accurate sorting)
df_events_raw['timestamp'] = pd.to_datetime(df_events_raw['timestamp'])

# Sort by trip_id and timestamp, then drop duplicates keeping the last (latest) entry.
df_events_raw.sort_values(by=['trip_id', 'timestamp'], inplace=True)
df_events_raw.drop_duplicates(subset=['trip_id'], keep='last', inplace=True)
print(f"Deduplicated events_raw size: {len(df_events_raw)} rows.")
# --- END FIX ---

# 1. Merge trips with raw event data to get the critical timestamp
df_analysis = df_trips.merge(
    df_events_raw[['trip_id', 'timestamp']],
    on='trip_id',
    how='left'
)

# Convert timestamp and calculate essential time features (timestamp is already datetime from the fix)
# df_analysis['timestamp'] = pd.to_datetime(df_analysis['timestamp']) # Removed: Redundant due to fix

# --- NEW ESSENTIAL TIME-BASED FEATURES ---

# Hour of day (as a numerical feature)
df_analysis['hour_of_day'] = df_analysis['timestamp'].dt.hour

# is_weekend: 5=Friday (start of weekend pricing), 6=Saturday, 0=Sunday
df_analysis['is_weekend'] = df_analysis['timestamp'].dt.weekday.isin([4, 5, 6]).astype(int)

# is_night: Pricing surcharge (e.g., 10 PM to 5 AM)
df_analysis['is_night'] = ((df_analysis['hour_of_day'] >= 22) | (df_analysis['hour_of_day'] < 5)).astype(int)

# 2. Merge with driver contract type (retains only relevant driver feature)
df_analysis = df_analysis.merge(
    df_drivers[['driver_id', 'contract_type']],
    on='driver_id',
    how='left'
)

# 3. Merge with car model (retains only relevant car feature)
df_analysis = df_analysis.merge(
    df_cars[['car_id', 'model']],
    on='car_id',
    how='left'
)

# Drop rows where key merges or timestamp conversion failed
df_analysis.dropna(subset=['driver_id', 'car_id', 'timestamp', 'model'], inplace=True)

print(f"Final Analytical Dataset size: {len(df_analysis)} rows.")

# Define the target variable (y)
TARGET = 'trip_cost'

# Define numerical and categorical predictors (UPDATED)
FEATURES_CATEGORICAL = ['trip_type', 'contract_type', 'model', 'is_weekend', 'is_night']
FEATURES_NUMERICAL = ['actual_dist_km', 'actual_time_min', 'hour_of_day']

# Select final features
df_ml = df_analysis[FEATURES_NUMERICAL + FEATURES_CATEGORICAL + [TARGET]].copy()

# Drop rows with any remaining missing data
df_ml.dropna(inplace=True)

# One-Hot Encoding for categorical variables
df_ml = pd.get_dummies(df_ml, columns=FEATURES_CATEGORICAL, drop_first=True)

# Define X (features) and y (target)
X = df_ml.drop(columns=[TARGET])
y = df_ml[TARGET]

print(f"\nModel X matrix columns (features): {X.columns.tolist()}")
print(f"X shape: {X.shape}, y shape: {y.shape}")

# Initialize StandardScaler and select numerical columns (UPDATED)
scaler = StandardScaler()
numerical_cols = FEATURES_NUMERICAL

# Perform initial Train/Test Split here before scaling (best practice)
X_train_raw, X_test_raw, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Fit and transform the training data
X_train_scaled = X_train_raw.copy()
X_test_scaled = X_test_raw.copy()

X_train_scaled[numerical_cols] = scaler.fit_transform(X_train_raw[numerical_cols])
X_test_scaled[numerical_cols] = scaler.transform(X_test_raw[numerical_cols])

print(f"\nTrain samples after scaling: {len(X_train_scaled)}")
print(f"Test samples after scaling: {len(X_test_scaled)}")

print("\n--- 3.1 Hyperparameter Optimization via GridSearchCV ---")

# 1. Model Definitions and Parameter Grids
models_and_params = {
    'KNN_Regressor': {
        'model': KNeighborsRegressor(),
        'params': {'n_neighbors': [5, 10, 15, 20],
                   'weights': ['uniform', 'distance']}
    },
    'Random_Forest_Regressor': {
        'model': RandomForestRegressor(random_state=42),
        'params': {'n_estimators': [50, 100, 200],
                   'max_depth': [5, 10, 15]}
    }
}

best_model = None
best_score = -np.inf # Use negative metric for scoring

# Dictionary to hold all trained models and their results
trained_models = {}

# Loop through models and perform Grid Search
for name, mp in models_and_params.items():
    print(f"\nStarting Grid Search for: {name}...")

    # Use scaled data for all models
    X_train_current = X_train_scaled

    grid_search = GridSearchCV(
        mp['model'],
        mp['params'],
        cv=3,
        scoring='neg_mean_squared_error', # Using negative MSE for maximization
        n_jobs=-1
    )

    grid_search.fit(X_train_current, y_train)

    # Save results
    trained_models[name] = grid_search

    # Check if this model is the new best
    current_score = grid_search.best_score_
    print(f"Best score (Negative MSE): {current_score:.4f}")
    print(f"Best parameters: {grid_search.best_params_}")

    if current_score > best_score:
        best_score = current_score
        best_model = grid_search.best_estimator_

print("\n--- Model Tuning Complete ---")
print(f"🏆 Overall Best Model: {type(best_model).__name__}")

print("\n--- 3.2 Final Evaluation of Best Model ---")

# Make predictions on the test set using the overall best model
y_pred = best_model.predict(X_test_scaled)

# --- Evaluation ---
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Model: {type(best_model).__name__}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} (Error in $)")
print(f"R-squared (R2 Score): {r2:.4f}")

# Visualize Residuals
plt.figure(figsize=(10, 6))
residuals = y_test - y_pred
sns.scatterplot(x=y_pred, y=residuals)
plt.axhline(y=0, color='r', linestyle='--')
plt.title(f'Residuals Plot for {type(best_model).__name__}')
plt.xlabel('Predicted Trip Cost ($)')
plt.ylabel('Residuals (Actual - Predicted) ($)')
plt.show() #

print("\n--- 4. MLOps: Model Persistence ---")

# Define file paths for the artifacts
MODEL_FILENAME = 'best_trip_cost_model.joblib'
SCALER_FILENAME = 'feature_scaler.joblib'

# 1. Save the best model
joblib.dump(best_model, MODEL_FILENAME)
print(f"✅ Best model saved to {MODEL_FILENAME}")

# 2. Save the feature scaler object (Crucial for live prediction preprocessing!)
joblib.dump(scaler, SCALER_FILENAME)
print(f"✅ Scaler object saved to {SCALER_FILENAME}")

print("\nDeployment Readiness Complete.")
print("The saved artifacts are ready to be integrated into a web service.")

# Final check: Load and test the persisted model
loaded_model = joblib.load(MODEL_FILENAME)
print(f"\nLoaded model type: {type(loaded_model).__name__}")