# -*- coding: utf-8 -*-
"""Reg&Class&ML

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kUKyuNy7LK-Zk6wg0tz14kxif8h8O4a3
"""

# --- 1. SETUP AND DATA LOADING ---
import pandas as pd
import numpy as np
import sys
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import seaborn as sns

# --- Neon Database Configuration ---
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_C9aUQXVxSGE6"
DB_HOST = "ep-cold-paper-adut66se-pooler.c-2.us-east-1.aws.neon.tech"
DB_NAME = "neondb"
DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}?sslmode=require&channel_binding=require"
engine = create_engine(DATABASE_URL)

# Load data by joining the necessary tables
query = """
SELECT
    em.trip_cost,
    em.trip_type,
    em.actual_time_min,
    em.actual_dist_km,
    em.timestamp,
    d.contract_type
FROM
    events_mixed em
LEFT JOIN drivers d ON em.driver_id = d.driver_id
WHERE
    em.trip_id IS NOT NULL AND em.cancellation_reason IS NULL;
"""
df = pd.read_sql(query, engine)

# --- 2. FEATURE ENGINEERING FOR ANALYSIS ---
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['hour_of_day'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.day_name()
df['day_type'] = np.where(df['day_of_week'].isin(['Saturday', 'Sunday']), 'Weekend', 'Weekday')

# Define time-of-day categories based on business logic
def get_time_of_day(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    elif 18 <= hour < 22:
        return 'Evening'
    else:
        return 'Night'

df['time_of_day'] = df['hour_of_day'].apply(get_time_of_day)

# --- 3. ADVANCED ANALYSIS & VISUALIZATION ---
print("\n--- Generating Advanced Analytics Reports ---")

# Analysis 1: Average Trip Cost by Time of Day and Day Type
avg_cost_df = df.groupby(['time_of_day', 'day_type'])['trip_cost'].mean().reset_index()
avg_cost_pivot = avg_cost_df.pivot(index='time_of_day', columns='day_type', values='trip_cost')

plt.figure(figsize=(10, 6))
sns.heatmap(avg_cost_pivot, annot=True, fmt=".2f", cmap="YlGnBu", cbar_kws={'label': 'Average Trip Cost ($)'})
plt.title('Average Trip Cost by Time of Day and Day Type')
plt.xlabel('Day Type')
plt.ylabel('Time of Day')
plt.tight_layout()
plt.savefig('avg_trip_cost_heatmap.png')
print("Generated heatmap: avg_trip_cost_heatmap.png")
plt.show()

# Analysis 2: Total Revenue by Trip Type
revenue_by_trip_type = df.groupby('trip_type')['trip_cost'].sum().sort_values(ascending=False).reset_index()
plt.figure(figsize=(12, 7))
sns.barplot(x='trip_cost', y='trip_type', data=revenue_by_trip_type, palette='viridis')
plt.title('Total Revenue by Trip Type')
plt.xlabel('Total Revenue ($)')
plt.ylabel('Trip Type')
plt.tight_layout()
plt.savefig('revenue_by_trip_type.png')
print("Generated bar chart: revenue_by_trip_type.png")
plt.show()

# Analysis 3: Revenue Distribution by Driver Contract Type
revenue_by_contract = df.groupby('contract_type')['trip_cost'].sum().reset_index()
plt.figure(figsize=(8, 8))
plt.pie(revenue_by_contract['trip_cost'], labels=revenue_by_contract['contract_type'], autopct='%1.1f%%', startangle=90, colors=sns.color_palette("pastel"))
plt.title('Total Revenue Distribution by Driver Contract Type')
plt.tight_layout()
plt.savefig('revenue_by_contract_type.png')
print("Generated pie chart: revenue_by_contract_type.png")
plt.show()

# --- 1. SETUP AND DATA LOADING ---
import pandas as pd
import numpy as np
import sys
import joblib
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
import re

# --- Neon Database Configuration ---
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_C9aUQXVxSGE6"
DB_HOST = "ep-cold-paper-adut66se-pooler.c-2.us-east-1.aws.neon.tech"
DB_NAME = "neondb"
DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}?sslmode=require&channel_binding=require"
engine = create_engine(DATABASE_URL)

# Corrected SQL query: ONLY selecting columns needed for the final, focused feature set.
query = """
SELECT
    em.actual_time_min,
    em.actual_dist_km,
    em.trip_cost,
    em.trip_type,
    em.timestamp
FROM
    events_mixed em
WHERE
    em.trip_id IS NOT NULL AND em.trip_cost IS NOT NULL;
"""
df_analysis = pd.read_sql(query, engine)

# --- 2. FEATURE ENGINEERING ---
df_analysis['timestamp'] = pd.to_datetime(df_analysis['timestamp'])
df_analysis['hour_of_day'] = df_analysis['timestamp'].dt.hour
df_analysis['is_weekend'] = df_analysis['timestamp'].dt.weekday.isin([4, 5, 6]).astype(int)
df_analysis['is_night'] = ((df_analysis['hour_of_day'] >= 22) | (df_analysis['hour_of_day'] < 5)).astype(int)

df_analysis.dropna(inplace=True)

# --- 3. DATA PREPROCESSING AND MODELING ---
# Define target and features
# Focused Features: Distance, Time, Service Type, and Time Indicators (Day/Night/Weekend)
FEATURES_CATEGORICAL = ['trip_type', 'is_weekend', 'is_night']
FEATURES_NUMERICAL = ['actual_dist_km', 'actual_time_min', 'hour_of_day']
TARGET = 'trip_cost'

df_ml = df_analysis[FEATURES_NUMERICAL + FEATURES_CATEGORICAL + [TARGET]].copy()
df_ml.dropna(inplace=True)
df_ml = pd.get_dummies(df_ml, columns=FEATURES_CATEGORICAL, drop_first=True)

X = df_ml.drop(columns=[TARGET])
y = df_ml[TARGET]

# Split and Scale
X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
numerical_cols = FEATURES_NUMERICAL
X_train_scaled = X_train_raw.copy()
X_test_scaled = X_test_raw.copy()
X_train_scaled[numerical_cols] = scaler.fit_transform(X_train_raw[numerical_cols])
X_test_scaled[numerical_cols] = scaler.transform(X_test_raw[numerical_cols])

# --- 4. MODEL TRAINING AND EVALUATION ---
# Train the best model found in the notebook: RandomForestRegressor
best_model = RandomForestRegressor(random_state=42)
best_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = best_model.predict(X_test_scaled)

# Evaluation
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)
print(f"Model: {type(best_model).__name__}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f} (Error in $)")
print(f"R-squared (R2 Score): {r2:.4f}")

# --- 5. MLOps: MODEL PERSISTENCE ---
# Note for GitHub: This step saves the trained model and scaler to disk for deployment.
MODEL_FILENAME = 'best_trip_cost_model.joblib'
SCALER_FILENAME = 'feature_scaler.joblib'

joblib.dump(best_model, MODEL_FILENAME)
joblib.dump(scaler, SCALER_FILENAME)

print("\nModel persistence complete.")
print(f"Model saved to: {MODEL_FILENAME}")
print(f"Scaler saved to: {SCALER_FILENAME}")

"""### **REGRESSION MODEL ANALYSIS**

This report analyzes the performance of the final, highly focused `RandomForestRegressor` model, which was trained specifically on the essential pricing factors (distance, time, service type, and time indicators).

---

## **1. Model Performance Summary**

| Metric | Score | Interpretation |
| :--- | :--- | :--- |
| **Root Mean Squared Error (RMSE)** | **$2.40** | **EXCEPTIONAL ACCURACY.** The model's predicted trip cost is, on average, only off by **\$2.40**. This is a slight improvement over the previous version and demonstrates high precision in cost forecasting. |
| **R-squared ($R^2$) Score** | **0.9957** | **OUTSTANDING FIT.** The model explains **99.57%** of the variability in the trip cost. This score confirms that the streamlined feature set is highly effective and captures the inherent logic of the pricing structure. |

---

## **2. The Critical Challenge: Overfitting Verification**

The model's scores are so high that they still suggest a potential issue with **overfitting**. We must treat this accuracy with caution until it's validated on diverse data.

* **High $R^2$ Score**: An $R^2$ score above $0.99$ remains the key indicator of potential overfitting. The model is effectively mirroring the test data and must be proven to generalize.
* **Low RMSE**: The consistently low RMSE reinforces the precision but doesn't dismiss the overfitting risk.

**Conclusion**: The model is highly accurate on the current test set. Before deployment, we must prioritize robust validation to ensure its stability when faced with real-world NOT GENERATED DATA, unseen data.

---

## **3. Next Steps: Ensuring Model Robustness**

To confirm this high accuracy is reliable and deployable, the focus must be on rigorous testing and validation:

1.  **Cross-Validation (Robust Testing)**: We must immediately implement **k-fold cross-validation** (e.g., using `KFold` or `cross_val_score` in Python). This will assess the model's stability across multiple data subsets and provide a final, trustworthy score for generalization.

2.  **Deployment Readiness**: Assuming cross-validation confirms stability, the saved artifacts (`best_trip_cost_model_v4_final.joblib` and `feature_scaler_v4_final.joblib`) are the definitive components for the production API. The high score justifies moving directly to deployment after validation.

the above text generate it with AI, just for rephrasing and making ready for python format
"""

# --- 1. SETUP AND DATA LOADING ---
import pandas as pd
import numpy as np
import sys
import joblib
from sqlalchemy import create_engine
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report
from collections import Counter

# Neon Database Configuration
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_C9aUQXVxSGE6"
DB_HOST = "ep-cold-paper-adut66se-pooler.c-2.us-east-1.aws.neon.tech"
DB_NAME = "neondb"
DATABASE_URL = f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}/{DB_NAME}?sslmode=require&channel_binding=require"
engine = create_engine(DATABASE_URL)

# SQL query to join necessary tables and retrieve only the required columns
query = """
SELECT
    em.trip_cost,
    em.actual_time_min,
    em.actual_dist_km,
    em.trip_type
FROM
    events_mixed em
WHERE
    em.trip_id IS NOT NULL AND em.trip_cost IS NOT NULL;
"""
df_trips = pd.read_sql(query, engine)

# 2. TARGET AND FEATURE DEFINITION ---
# Define the target based on the 75th percentile cost (Q3)
Q3_COST = df_trips['trip_cost'].quantile(0.75)
df_trips['is_high_value'] = (df_trips['trip_cost'] >= Q3_COST).astype(int)

# Define Focused Feature Set
# Numerical features are the direct physical inputs
FEATURES_NUMERICAL = ['actual_dist_km', 'actual_time_min']
# Categorical features that define the service level
FEATURES_CATEGORICAL = ['trip_type']
TARGET = 'is_high_value'

df_ml = df_trips[FEATURES_NUMERICAL + FEATURES_CATEGORICAL + [TARGET]].copy()
df_ml.dropna(inplace=True)

# 3. DATA PREPROCESSING AND IMBALANCE HANDLING
# One-Hot Encoding for trip_type
df_ml = pd.get_dummies(df_ml, columns=FEATURES_CATEGORICAL, drop_first=True)

X = df_ml.drop(columns=[TARGET])
y = df_ml[TARGET]

# Split data
X_train_raw, X_test_raw, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Apply SMOTE to training data to handle imbalance
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train_raw, y_train)
print(f"Dataset balanced via SMOTE. New Train Size: {len(X_train_balanced)}")

# Feature Scaling
scaler = StandardScaler()
numerical_cols = FEATURES_NUMERICAL # Scale distance and time
scaler.fit(X_train_raw[numerical_cols])
X_train_final = X_train_balanced.copy()
X_train_final[numerical_cols] = scaler.transform(X_train_balanced[numerical_cols])
X_test_scaled = X_test_raw.copy()
X_test_scaled[numerical_cols] = scaler.transform(X_test_raw[numerical_cols])

# 4. MODEL TRAINING AND EVALUATION
# Train the model
best_model = RandomForestClassifier(random_state=42)
best_model.fit(X_train_final, y_train_balanced)

# Make predictions and evaluate
y_pred = best_model.predict(X_test_scaled)
y_prob = best_model.predict_proba(X_test_scaled)[:, 1]

f1 = f1_score(y_test, y_pred)
roc_auc = roc_auc_score(y_test, y_prob)
print(f"\n--- Model Performance (Focused Features) ---")
print(f"Model: {type(best_model).__name__}")
print(f"F1 Score (High Value Trips): {f1:.4f}")
print(f"ROC AUC Score: {roc_auc:.4f}")
print("\nClassification Report (Focus on Precision/Recall):")
print(classification_report(y_test, y_pred))

# --- 5. MLOps: MODEL PERSISTENCE ---
MODEL_FILENAME_CLF = 'best_profitability_classifier.joblib'
SCALER_FILENAME_CLF = 'feature_scaler_profitability.joblib'

joblib.dump(best_model, MODEL_FILENAME_CLF)
joblib.dump(scaler, SCALER_FILENAME_CLF)

print("\nModel persistence complete.")
print(f"Model saved to: {MODEL_FILENAME_CLF}")
print(f"Scaler saved to: {SCALER_FILENAME_CLF}")

"""### **CLASSIFICATION MODEL ANALYSIS**

The final classification model was built with a **focused feature set** (distance, time, and trip type) and achieved exceptional results, indicating a solution that is near-perfect for operational deployment.

---

## **1. Model Performance Summary**

| Metric | Score | Interpretation |
| :--- | :--- | :--- |
| **ROC AUC Score** | **1.0000** | **PERFECT DISCRIMINATION.** The model can flawlessly separate high-value from normal trips. This confirms the selected features are the fundamental drivers of trip cost. |
| **F1 Score (Class 1)** | **0.9873** | **OUTSTANDING RELIABILITY.** This score shows near-perfect balance between finding the trips and confirming they are correct. |
| **Accuracy** | 0.99 | **TRUSTWORTHY.** This high score is reliable because performance is equally strong across both the minority and majority classes. |

---

## **2. Detailed Breakdown: Business Impact**

The focused model fixed the major issue from Version 2: low precision.

| Metric | Class 1 (High-Value Trip) Score | Business Impact |
| :--- | :--- | :--- |
| **Recall** | **1.00 (100%)** | **PERFECT CAPTURE.** We identify **100%** of all actual high-value trips. No valuable opportunities are missed. |
| **Precision** | **0.97 (97%)** | **HIGHLY ACTIONABLE.** When the model flags a trip as high-value, it is correct **97%** of the time. This eliminates false alarms, allowing operations to trust the prediction stream. |

**Conclusion**: The focused feature set (distance, time, and service type) provided the model with the exact information needed. The model is stable, highly accurate, and has achieved its theoretical maximum predictive power on this dataset.

---

## **3. Next Steps: MLOps and Deployment**

Since performance is effectively perfect, the project shifts entirely to operational readiness.

1.  **Skip Tuning**: Hyperparameter optimization is unnecessary (ROC AUC of 1.0000).
2.  **Deployment Verification**: The saved artifacts (`.joblib` files) are now the primary focus. The next step is building the API wrapper to integrate the model's predictions into the company's live systems.

the above text generate it with AI, just for rephrasing and making ready for python format
"""

"""
README:
This script serves as a final MLOps step, ensuring the trained models
are ready for deployment. It saves the best-performing models and their
preprocessors (e.g., StandardScaler) to disk.

Workflow:
1. Load the best-performing models from your previous scripts.
2. Save the models and scalers using joblib.
3. Verify that the artifacts have been saved.

Note for GitHub: This file should be placed in the project's 'src' directory.
Dependencies: joblib
"""
import joblib

# --- Dummy placeholders for the models (in a real scenario, you would import them from your training scripts) ---
# Assuming you have run the classification and regression scripts and saved the models
try:
    # --- Corrected filenames from your last runs ---
    best_classifier = joblib.load('best_profitability_classifier.joblib')
    classifier_scaler = joblib.load('feature_scaler_profitability.joblib')
    best_regressor = joblib.load('best_trip_cost_model.joblib')
    regressor_scaler = joblib.load('feature_scaler.joblib')
    print("All model artifacts loaded successfully.")
except FileNotFoundError:
    print("Error: Model files not found. Please run the training scripts first.")
    exit()

# --- 1. DEFINE FILE PATHS ---
MODEL_FILENAMES = {
    'classifier_model': 'best_profitability_classifier.joblib',
    'classifier_scaler': 'feature_scaler_profitability.joblib',
    'regressor_model': 'best_trip_cost_model.joblib',
    'regressor_scaler': 'feature_scaler.joblib'
}

# --- 2. VERIFY AND REPORT ARTIFACTS ---
print("\n--- MLOps: Deployment Readiness Report ---")
for name, filename in MODEL_FILENAMES.items():
    if joblib.load(filename):
        print(f"✔ Artifact '{name}' is ready at '{filename}'.")
    else:
        print(f"✗ Error: Artifact '{name}' not found.")

print("\nDeployment Readiness Complete. The artifacts are ready for a production API.")

"""1. The MLOps script successfully located and loaded all the necessary files, which are now verified and ready to be integrated into a production API.

*   Classification Model (best_profitability_classifier.joblib): This model is ready to predict whether a new trip will be a "high-value trip."
*   Classification Scaler (feature_scaler_profitability.joblib): This preprocessing tool is essential for scaling new data before it's fed into the classification model, ensuring accurate predictions.
*   Regression Model (best_trip_cost_model.joblib): This model is ready to predict the cost of a new trip.
*   Regression Scaler (feature_scaler.joblib): This scaler is needed to preprocess new data for the regression model, ensuring the model's predictions are reliable.

2. Next Step:
All the necessary components—the trained models and their scalers—have been saved to disk and are ready to be used by a production API or web service.

- Build a Prediction API: Create a simple web service (e.g., using Flask FastAPI) that can load these models and scalers to make real time predictions on new data.

- Integrate with Business Systems: The prediction API can be integrated with my company's operational systems to, for example, alert managers when a high value trip is detected or to automatically quote a trip price.

- Monitoring and Retraining: In a real world scenario, I would need to monitor the models' performance over time and retrain them periodically with new data to ensure their accuracy doesn't degrade.
"""

